FROM constellation-base

# copy the current directory contents into the container at /constellation, excluding the files in .dockerignore
COPY ../.. /constellation

# set the working directory to /constellation
WORKDIR /constellation

# build the project
RUN mkdir -p build && cd build && cmake .. && cmake --build .

# install the python package
WORKDIR /constellation/python
RUN pip3 install .

RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*


