FROM pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime

# cmake build tools
RUN env | grep -i _PROXY
RUN apt-get update && apt-get install -y --no-install-recommends cmake gcc g++ make libc6-dev ninja-build unzip libzmq3-dev autoconf automake libtool wget

# install protobuf
WORKDIR /tmp
RUN wget https://github.com/protocolbuffers/protobuf/archive/refs/tags/v3.19.1.zip && \
    unzip v3.19.1.zip && \
    cd protobuf-3.19.1 && \
    ./autogen.sh && \
    ./configure && \
    make -j$(nproc) && \
    make install && \
    ldconfig

# clean up
RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN rm -rf /tmp/*

# fix for libstdc++ issue. Optional, but may be necessary for some systems
RUN mv /opt/conda/lib/libstdc++.so.6 /opt/conda/lib/libstdc++.so.6.bak
ENV PATH=/opt/conda/bin:/usr/local/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH